src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Table(name: "user")]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: "username", message: "Le username est déjà utilisé")]
#[UniqueEntity(fields: "mail", message: "L'email est déjà utilisé")]
#[UniqueEntity(fields: "token", message: "Erreur, token non unique")]

class User implements UserInterface,PasswordAuthenticatedUserInterface
{

    #[ORM\Column(name: "id", type: "integer")]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    private ?int $id = null;

    #[ORM\Column(name: "username", type: "string", length: 191, unique: true)]
    private ?string $username = null;

    #[ORM\Column(name: "prenom", type: "string", length: 191, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(name: "nom", type: "string", length: 191, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(name: "mail", type: "string", length: 191, unique: true)]
    #[Assert\Email()]
    private ?string $mail = null;

    #[ORM\Column(name: "password", type: "string", length: 191)]
    private ?string $password = null;

    #[ORM\Column(name: "token", type: "string", length: 191, unique: true)]

    private ?string $token = null;

    #[ORM\Column(name: "token_validity", type: "datetime")]
    #[Assert\Type("DateTime")]
    private ?\DateTimeInterface $tokenValidity = null;

    #[ORM\Column(name: "salt", type: "string", length: 191, nullable: true)]
    private ?string $salt = null;

    #[ORM\Column(name: "is_active", type: "boolean")]
    private ?bool $isActive = null;

    #[ORM\Column(name: "roles", type: "array")]
    private ?array $roles = array();

    #[ORM\ManyToMany(targetEntity: Film::class, mappedBy: "usersWantToView")]
    private ?Collection $films = null;

    #[ORM\ManyToMany(targetEntity: Film::class, mappedBy: "usersWhoSeen")]
    private ?Collection $filmsVus = null;

    #[ORM\OneToOne(targetEntity: Profile::class, mappedBy: "user", cascade: ["persist", "remove"])]
    private ?Profile $profile = null;

    #[ORM\Column(name: "last_activity", type: "datetime")]
    #[Assert\Type("DateTime")]
    private ?\DateTimeInterface $lastActivity = null;

    public function getLastActivity(): ?\DateTimeInterface
    {
        return $this->lastActivity;
    }

    public function setLastActivity(?\DateTimeInterface $lastActivity): self
    {
        $this->lastActivity = $lastActivity;

        return $this;
    }

    public function isActiveNow(): ?bool
    {
        $delay = new \DateTime('5 minutes ago');

        return ( $this->getLastActivity() > $delay );
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getUsername(): ?string
    {
        return (string) $this->username;
    }

    public function getUserIdentifier(): string
    {
        return $this->username;
    }

    public function setActivated(?bool $activated): self
    {
        $this->isActive = $activated;

        return $this;
    }

    public function getActivated(): ?bool
    {
        return $this->isActive;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(?string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPassword() : ?string
    {
        return $this->password;
    }

    public function setSalt(?string $salt): self
    {
        $this->salt = $salt;

        return $this;
    }

    public function getSalt(): ?string
    {
        return $this->salt;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        //$this->token = hash("sha512", uniqid());
        $this->token = $token;
        $this->setTokenValidity(new \DateTime());

        return $this;
    }

    public function getTokenValidity(): ?\DateTimeInterface
    {
        return $this->tokenValidity;
    }

    private function setTokenValidity(?\DateTimeInterface $tokenValidity): self
    {
        $this->tokenValidity = $tokenValidity;

        return $this;
    }

    public function isValidToken(): ?bool
    {
        $expire = (new \DateTime($this->getTokenValidity()->format("Y-m-d H:i:s")))->modify('+1 hour');
        dump($expire);
        dump(new \DateTime('now'));
        return ( $expire > new \DateTime('now') );
    }

    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);

    }

    public function eraseCredentials(): void
    {

    }

    public function __construct()
    {
        $this->films = new \Doctrine\Common\Collections\ArrayCollection();
        //$this->setToken();
        $this->setLastActivity(new \DateTime('now'));
        $this->setActivated(true);
    }

    ///////////////////////////////////////////////////////////////
   
    public function addFilm(Film $film): self
    {
        $this->films[] = $film;

        return $this;
    }

    public function removeFilm(Film $film): self
    {
        $this->films->removeElement($film);

        return $this;
    }

    public function getFilms(): Collection
    {
        return $this->films;
    }

    ///////////////////////////////////////////////////////////////////////////

    public function addFilmVu(Film $film): self
    {
        $this->filmsVus[] = $film;

        return $this;
    }

    public function removeFilmVu(Film $film): self
    {
        $this->filmsVus->removeElement($film);

        return $this;
    }

    public function getFilmsVus(): Collection
    {
        return $this->filmsVus;
    }

    public function getNomComplet(): ?string
    {
        if ($this->prenom == null && $this->nom == null)
        {
            return $this->getUserIdentifier();
        } else
        return $this->getPrenom()." ".$this->getNom();
    }

    public function isAccountNonExpired(): ?bool
    {
        return true;
    }

    public function isAccountNonLocked(): ?bool
    {
        return true;
    }

    public function isCredentialsNonExpired(): ?bool
    {
        return true;
    }

    public function isEnabled(): ?bool
    {
        return $this->isActive;
    }

    public function serialize(): ?string
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive,
            // see section on salt below
            // $this->salt,
        ));
    }

    public function unserialize(?string $serialized):void 
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->isActive,

            // see section on salt below
            // $this->salt
            ) = unserialize($serialized, array('allowed_classes' => false));
    }

    public function wantToSee(Film $film): ?bool
    {
        return $this->getFilms()->contains($film);
    }

    public function haveSeen(Film $film): ?bool
    {
        return $this->getFilmsVus()->contains($film);
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(?Profile $profile): self
    {
        // set the owning side of the relation if necessary
        if ($profile->getUser() !== $this) {
            $profile->setUser($this);
        }

        $this->profile = $profile;

        return $this;
    }

}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\Profile;
use App\Form\UserEditPasswordType;
use App\Form\UserEditType;
use App\Form\UserRegisterType;
use App\Service\Mail;
use App\Service\UserManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\UserType;
use App\Entity\User;
use App\Form\ProfileType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\HttpFoundation\Response;


class SecurityController extends AbstractController
{
    #[Route("/login", name: "app_login")]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route("/logout", name: "app_logout")]
    public function logout()
    {
        throw new \Exception('Don\'t forget to activate logout in security.yaml');
    }

    #[Route("/admin/createuser", name: "admin_createuser")]
    public function createUserAction(Request $request, UserManager $userManager): Response
    {
        $user = new User;
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $userManager->enregistrerUser($user);
            $this->addFlash('success', 'L\'utilisateur a été ajouté');
            return $this->redirectToRoute('admin_index');
        }
        return $this->renderForm('security/createuser.html.twig', array (
            'form'  => $form
        ));
    }

    #[Route("/admin/edituser/{id}", name: "admin_edituser")]
    public function editUserAction(Request $request, User $user, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $em->flush();
            $this->addFlash('success', 'L\'utilisateur a été modifié');
            return $this->redirectToRoute('admin_index');
        }
        return $this->renderForm('security/createuser.html.twig', array (
            'form'  => $form
        ));
    }

    #[Route("/admin/edituseroptions/{id}", name: "admin_edituseroptions")]
    public function editUseroptions (Request $request, Profile $options, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(ProfileType::class, $options);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $em->flush();
            $this->addFlash('success', 'Les options de l\'utilisateur ont bien été modifiées.');

            return $this->redirectToRoute('admin_index');
        }
        
        return $this->renderForm('profil/preferences.html.twig', [
            'user'  => $options->getUser(),
            'form'  => $form
        ]);
    }

    #[Route("/admin", name: "admin_index")]
    public function indexAction(Request $request, UserRepository $repo): Response
    {
        $users = $repo->findAll();

        return $this->render('security/liste.html.twig', array(
            'users' => $users
        ));
    }

    #[Route("/admin/deluser/{id}", name: "admin_deluser")]
    public function delUserAction (Request $request, User $user, UserManager $userManager, FormFactoryInterface $ffi): Response
    {
        $form = $ffi->create();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $userManager->removeUser($user);
            $this->addFlash("success", "L'utilisateur a bien été supprimé");
            return $this->redirectToRoute('admin_index');
        }
        return $this->renderForm('security/supprimeruser.html.twig', array (
            'user'  =>  $user,
            'form'  =>  $form
        ));
    }

    #[Route("/register", name: "security_register")]
    public function registerAction(Request $request, UserManager $userManager, Mail $mail): Response
    {
        $user = new User();
        $form = $this->createForm(UserRegisterType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $userManager->register($user);

            //$adresse = $this->generateUrl('security_activate', array('token'=>$user->getToken()), UrlGeneratorInterface::ABSOLUTE_URL);
            //$mail->sendMailActivation($user, $adresse);
            
            $adresse = $this->generateUrl('admin_edituser', ['id' => $user->getId()], UrlGeneratorInterface::ABSOLUTE_URL);
            $mail->sendMailDemandeActivation($user, $adresse);

            $this->addFlash('success', 'Votre compte a été créé. Un mail a été envoyé à l\'administrateur pour l\'activation du compte');
            return $this->redirectToRoute('security_attente');
        }

        return $this->renderForm('security/register.html.twig', [
            'form'  => $form
        ]);
    }

    #[Route("/attente", name: "security_attente")]
    public function attenteActivation(): Response
    {
        return $this->render('security/attente.html.twig');
    }

    #[Route("/motdepasseoublie", name: "security_envoyertoken")]
    public function recupMdpAction(Request $request, UserManager $userManager, Mail $mail, EntityManagerInterface $em, UserRepository $userRepo): Response
    {
        $form = $this->createFormBuilder()
            ->add('email', EmailType::class)
            ->add('envoyer-mail', SubmitType::class)
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $user = $userRepo->findOneBy(array('mail'=>$data['email']));
            if ($user != null)
            {
                $userManager->generateToken($user);
                $em->flush();
                $adresse = $this->generateUrl('security_resetpassword', array('token'=>$user->getToken()), UrlGeneratorInterface::ABSOLUTE_URL);

                $mail->sendMailTokenMp($user, $adresse);

                $this->addFlash('success', "Un mail vous a été envoyé à ".$user->getUsername()." pour récupérer le mot de passe");
                return $this->redirectToRoute('app_login');
            } else {
                $this->addFlash('warning', "Cet email n'existe pas");
            }
        }
        return $this->renderForm('security/chercheruserpourpassword.html.twig', array (
            'form'  =>  $form
        ));
    }

    #[Route("/resetpassword/token={token}", name: "security_resetpassword")]
    public function resetPasswordAction(Request $request, UserManager $userManager, User $user = null): Response
    {
        if ($user != null) {
            if ($user->isValidToken()) {
                $form = $this->createForm(UserEditPasswordType::class, $user);
                $form->handleRequest($request);
                if ($form->isSubmitted() && $form->isValid()) {
                    $userManager->resetPassword($user);
                    $this->addFlash('success', 'Mot de passe changé, veuillez vous connecter');
                    return $this->redirectToRoute('videotheque_liste');
                }
                return $this->renderForm('security/password.html.twig', array(
                    'form' => $form
                ));
            }
        }
        $this->addFlash('warning', "Ce token n'est plus valide");
        return $this->redirectToRoute('videotheque_liste');

    }

    #[Route("/admin/resettokens", name: "admin_resettokens")]
    public function resetTokensAction(UserManager $userManager, EntityManagerInterface $em, UserRepository $userRepo): Response
    {
        $users = $userRepo->findAll();
        foreach ($users as $user)
        {
            $userManager->generateToken($user);
        }
        $em->flush();
        return $this->redirectToRoute('admin_index');
    }

    #[Route("/activate/token={token}", name: "security_activate")]
    public function activateAction(Request $request, EntityManagerInterface $em, User $user = null): Response
    {
        if ($user != null)
        {
            if ($user->isValidToken())
            {
                $user->setActivated(true);
                $em->flush();
                $this->addFlash('success', "Votre compte est activé");
                return $this->redirectToRoute('app_login');
            }
        }
        $this->addFlash('warning', "Ce token n'est plus valide");
        return $this->redirectToRoute('videotheque_liste');
    }
}

templates/security/attente.html.twig
{% extends 'base.html.twig' %}

{% block title %}En attente{% endblock %}

{% block body %}
    <h1>En attente de validation</h1>
    <p>Votre demande d'activation a été envoyé à l'administrateur qui la prendra en charge rapidement.</p>
    <p>Pour rappel, cette application est réservée à mes connaissances, je me réserve donc le droit de refuser l'activation du compte.</p>
    <p>Merci de votre compréhension.</p>
    <a href="{{ path('videotheque_liste') }}" class="btn btn-link">Retour à la liste des films</a>
{% endblock %}

templates/security/chercheruserpourpassword.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Récupérer mot de passe{%  endblock %}
{% block titre %}Récupérer mot de passe{%  endblock %}

{% block body %}
    <h2>Veuillez entrer votre adresse mail</h2>
    {{ form(form) }}
{% endblock %}

templates/security/createuser.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Créer un utilisateur{%  endblock %}
{% block titre %}Création d'un utilisateur{%  endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        {{ form(form) }}
    </div>
    <a href="{{ path('admin_index') }}" class="btn btn-link" role="button">Retour à la liste</a>
{% endblock %}

templates/security/liste.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Liste des utilisateurs{%  endblock %}
{% block titre %}Liste des utilisateurs{%  endblock %}

{% block body %}
    <p><a class="btn btn-primary" href="{{  path("admin_createuser") }}" role="button">Créer un utiliisateur</a></p>

    <table class="table table-bordered table-hover table-sm">
        <thead class="thead-dark">
        <tr>
            <th>En ligne</th>
            <th>Username</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Mail</th>
            <th>Dernière connexion</th>
            {#<th>Test Mail</th>#}
            <th>Roles</th>
            <th>Activé</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td >
                    {% if user.activeNow %}
                        <i class="fa fa-user text-success"></i>
                    {% else %}
                        <i class="fa fa-user-o text-secondary"></i>
                    {% endif %}
                </td>
                <td>{{ user.username }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.mail }}</td>
                <td>{{ user.lastActivity | date("d/m/Y H:i")}}</td>
                {#<td><a href="{{ path('admin_sendmailtest', {"id": user.id}) }}">Envoyer un mail test</a></td>#}
                <td>{% for role in user.roles %}<p>{{ role }}</p>{% endfor %}</td>
                <td>{{ user.enabled }}</td>
                <td>
                    {%  if user != app.user %}
                        <a href="{{ path('admin_deluser', {'id': user.id})  }}"><i class="fa fa-trash fa-lg text-danger"></i></a>
                    {%  endif %}
                    <a href="{{ path('admin_edituser', {'id': user.id})  }}"><i class="fa fa-edit fa-lg text-primary"></i></a>
                    <a href="{{ path('admin_edituseroptions', {'id': user.profile.id}) }}"><i class="fa fa-cog fa-lg"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - S'identifier{%  endblock %}
{% block titre %}Identification{%  endblock %}

{% block body %}
        <div class="row">
            <div class="col-md-4">
                <form method="post">
                    {% if error %}
                        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                    {% endif %}
                    <label for="inputUsername" class="sr-only">Login</label>
                    <div class="input-group mb-3">
                        <input type="text" value="{{ last_username }}" name="username" id="inputUsername" class="form-control" placeholder="Login" required autofocus>
                    </div>
                    <label for="inputPassword" class="sr-only">Mot de passe</label>
                    <div class="input-group mb-3">
                        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Mot de passe" required>
                    </div>
                    <input type="hidden" name="_csrf_token"
                        value="{{ csrf_token('authenticate') }}"
                    >

                    {#
                        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
                        See https://symfony.com/doc/current/security/remember_me.html
                    #}
                        <div class="checkbox mb-3">
                            <input type="checkbox" name="_remember_me">
                            <label for="remember_me">Se souvenir de moi</label>
                        </div>
                    

                    <button class="btn btn-primary mb-3" type="submit">
                        Se connecter
                    </button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="hr">
                <p>Pas de compte ? <a href="{{ path('security_register') }}">S'enregistrer</a></p>
                <p>Mot de passe oublié ? <a href="{{ path('security_envoyertoken') }}">Récupérer mot de passe</a></p>
            </div>
        </div>
{% endblock %}

templates/security/mail_activate.html.twig
Bonjour {{ user.nomComplet }},

Votre compte est bien enregistré, merci de cliquer sur le lien suivant pour l'activer (valable 1h)

{{ lien }}

A++
François

templates/security/mail_demande_activation.html.twig
Bonjour,

L'utilisateur {{ user.username }} vient de s'enregistrer sur la vidéothèque.
Veuillez vérifier les informations ci-dessous et vous assurer qu'il s'agit d'une connaissance.

Nom : {{ user.nom }}
Prénom : {{ user.prenom }}
Mail : {{ user.mail }}

Accéder au compte utilisateur : {{ lien }}

-- 
L'administrateur tout puissant

templates/security/mail_tokenmdp.html.twig
Bonjour {{ user.nomComplet }},

Voici le lien pour modifier votre mot de passe. Il est valable 1 heure.

{{ lien }}

A++
François

templates/security/password.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Changer de mot de passe{%  endblock %}
{% block titre %}Changer de mot de passe{%  endblock %}

{% block body %}
    <h2>Vous pouvez changer de mot de passe ici</h2>
    <div class="d-flex justify-content-center">
        {{ form(form) }}
    </div>
{% endblock %}

templates/security/register.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - S'enregistrer{%  endblock %}
{% block titre %}S'enregistrer{%  endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        {{ form(form) }}
    </div>
{% endblock %}

templates/security/supprimeruser.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Supprimer un utilisateur{% endblock %}
{% block titre %}Supprimer un utilisateur{% endblock %}

{% block body %}
    <h2>Confirmation ?</h2>
    <p>Êtes vous certain de vouloir supprimer l'utilisateur "{{ user.username }}" ?</p>
    <form action="{{ path('admin_deluser', {'id': user.id}) }}" method="post">
        <a href="{{ path('admin_index') }}" class="btn btn-secondary">
            <i class="fa fa-chevron-circle-left fa-lg"></i>
            Retour à la liste des utilisateurs
        </a>
        {# Ici j'ai écrit le bouton de soumission à la main #}
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {# Ceci va générer le champ CSRF #}
        {{ form_rest(form) }}
    </form>
{% endblock %}